app/blog/urls.py
from django.urls import path
from .views import BlogHome, BlogGenerador,BlogDetalle, BlogCrear, BlogActualizar

app_name = 'blog'
urlpatterns = [
    path('', BlogHome.as_view(), name='home'),
    path('detalle/<int:pk>/', BlogDetalle.as_view(), name='detalle'),
    path('generador/', BlogGenerador.as_view(), name='generador'),
    path('crear/', BlogCrear.as_view(), name="crear"),
    path('actualizar/<int:pk>/', BlogActualizar.as_view(), name="actualizar"),

]

app/vistas/urls.py
from django.contrib import admin
from django.urls import path, include

# app_name = 'actividades'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('actividades/', include('actividades.urls')),
    path('blog/', include('blog.urls')),
]

app/blog/models.py
from django.db import models

class EntradaBlog(models.Model):
    titulo =models.CharField(max_length=32, null=False, verbose_name="titulo", blank=True)
    contenido = models.TextField(verbose_name='Contenido')

    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    fecha_actualizacion = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")
    
    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = "Entrada de blog"
        verbose_name_plural = "Entradas de blog"
        ordering = ['-fecha_creacion']

app/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from .models import EntradaBlog
import pdb
import lorem
import random
from django.urls import reverse ,reverse_lazy

class BlogHome(ListView):
    model = EntradaBlog
    template_name = 'blog/home.html'
    paginate_by = 10

class BlogGenerador(View):
    def get(self, request):
        return render(request, template_name='blog/generador.html')
    
    def post(self, request):
        cantidad = int(request.POST.get('cantidad', 0))
        

        for _ in range(cantidad):
            numr = random.randint(0, 10000)
            entradablog = EntradaBlog()
            entradablog.titulo = lorem.sentence()
            entradablog.contenido = lorem.paragraph()
            entradablog.save()
            
        return redirect('blog:home')

class BlogDetalle(DetailView):
    model = EntradaBlog
    template_name = 'blog/detalle.html'

class BlogCrear(CreateView):
    extra_context = {'accion': 'Crear'}
    template_name = 'blog/crear-actualizar.html'
    
    model = EntradaBlog
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('blog:home')

    def post(self, request, *args, **kwargs):
        resp = super().post(request, *args, **kwargs)

        return resp

class BlogActualizar(UpdateView):
    extra_context = {'accion': 'Actualizar'}
    template_name = 'blog/crear-actualizar.html'

    model = EntradaBlog
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('blog:home')

    def get_success_url(self):
        return reverse('blog:detalle', args=(self.kwargs['pk'],))
    

app/blog/templates/blog/actualizar.html
{% extends 'blog/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">{{accion|title}} Blog</h1>
</div>

<div class="container">
    <form class="bg-light border my-5 p-3 rounded shadow" method="post">
        {% csrf_token %}
        <div class="my-3">

            <div class="form-floating my-3">
                <input type="text" class="form-control" id="et_titulo" placeholder="x" name="titulo" value="{{entradablog.titulo}}" required>
                <label for="et_titulo">Título</label>
            </div>

            <div class="form-floating my-3">
                <textarea class="form-control" placeholder="x" id="et_contenido" style="height:100px" name="contenido">{{entradablog.contenido}}</textarea>
                <label for="et_contenido">Contenido</label>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            
        </div>
    </form>
</div>

{% endblock %}

app/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Actividades</title>
</head>
<body>
    {% url 'blog:home' as url_home %}
    {% url 'blog:generador' as url_generador %}
    {% url 'blog:crear' as url_crear %}

    <div class="container-fluid bg-primary p-5">
        <h1 class="display-5 text-white">Entradas de Blogs</h1>
    </div>

    <div class="container-fluid px-0 sticky-{}">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark py-2">
            <div class="container-fluid">
                <!-- Logo o marca -->
                <a class="navbar-brand" href="">
                    <span><i class="fa-brands fa-html5"></i></span>
                </a>
                
                <!-- Botón para mostrar y ocultar el menú (solo visible cuando está colapsado)
                El target tiene que concidir con el ID del contenido del navbar -->
                <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#contenido_navbar" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="contenido_navbar">
                    <!-- .me-auto es para que todo lo que esté fuera de la lista
                    se pegue al lado derecho -->
                    <ul class="navbar-nav me-auto mb-0 pt-3 pt-sm-0">
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_home %} active {% endif %}" href="{% url 'blog:home' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_generador %} active {% endif %}" href="{% url 'blog:generador' %}">Generador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == url_crear %}active{% endif %}" href="{% url 'blog:crear' %}">Crear</a>
                        </li>
                    </ul>
                    <div class="d-flex pt-3 pt-sm-0 me-2 text-light flex-column flex-sm-row gap-3">
                        <a class="text-decoration-none text-light me-3" href="">Cerrar sesión</a>
                        <a class="text-decoration-none text-light me-3" href="">Cuenta</a>
                        <span class="d-none d-sm-inline"><i class="fa-solid fa-user"></i></span>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    {% block contenido %}{% endblock %}

</body>
</html>

app/blog/templates/blog/crear-actualizar.html
{% extends 'blog/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">{{accion|title}} Blog</h1>
</div>

<div class="container">
    <form class="bg-light border my-5 p-3 rounded shadow" method="post">
        {% csrf_token %}
        <div class="my-3">

            <div class="form-floating my-3">
                <input type="text" class="form-control" id="et_titulo" placeholder="x" name="titulo" value="{{entradablog.titulo}}" required>
                <label for="et_titulo">Título</label>
            </div>

            <div class="form-floating my-3">
                <textarea class="form-control" placeholder="x" id="et_contenido" style="height:100px" name="contenido">{{entradablog.contenido}}</textarea>
                <label for="et_contenido">Contenido</label>
            </div>

            <button type="submit" class="btn btn-primary">Guardar</button>
            
        </div>
    </form>
</div>

{% endblock %}

app/blog/templates/blog/detalle.html
{% extends 'blog/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Detalle de Blog</h1>
</div>

<div class="container">
    <p class="lead"> <strong> Titulo:</strong> {{entradablog.titulo}}</p>
    <p class="lead"> <strong> Contenido:</strong> {{entradablog.contenido}}</p>
    <p class="lead"> <strong> Fecha de creacion:</strong> {{entradablog.fecha_creacion|date:'d/m/y'}}</p>
    <p class="lead"> <strong> Fecha de actualizacion:</strong> {{entradablog.fecha_actualizacion|date:'d/m/y'}}</p>
    <a href="{% url 'blog:actualizar' entradablog.id %}" class="btn btn-primary">Editar</a>
</div>
{% endblock %}

app/blog/templates/blog/generador.html
{% extends 'blog/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Generador de Blogs</h1>
</div>

<div class="container">
    <!-- Como queremos que el formulario se envíe a la misma ruta, no nocesitamos el atributo action -->
    <form class="bg-light border mt-3 p-3 rounded shadow" method="post">
        <!-- Entradas agrupadas: .input-group .input-group-text -->
        {% csrf_token %}
        <div class="my-3">
            <div class="input-group my-1">
                <span class="input-group-text">Generar</span>
                <input type="number" min="1" class="form-control" name="cantidad" placeholder="" value="">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Generar</button>
    </form>
</div>

{% endblock %}

app/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Lista de Blogs</h1>
</div>

<div class="container my-5 d-flex flex-column justify-content-end gap-3">

    {% for entradablog in entradablog_list %}
            <div class="p-3 border rounded-3 shadow-sm">
            <div>
                <a href="{% url 'blog:detalle' entradablog.id %}" class="list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{entradablog.titulo}}</h5>
                    </div>
                    <p class="mb-1">{{entradablog.contenido| slice:100}}...</p>
                </a>
            </div>
        </div>
    {% endfor %}
    
</div>

<!-- Paginacion --> 
<div class="container my-5">
    <ul class="pagination pagination-lg justify-content-center my-5">
        <li class="page-item {% if not page_obj.has_previous %}active{% endif %}">
            <a class="page-link" href="?{{param_get}}&page=1">1</a>
        </li>

        {% if page_obj.paginator.num_pages >= 6 and page_obj.number >= 4 %}
        <li class="page-item disabled">
            <a class="page-link px-1" href="">{{page_obj.paginator.ELLIPSIS}}</a>
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 3 %}
        <li class="page-item">
            {% if page_obj.number <= 3 or page_obj.paginator.num_pages < 5 %}
                <a class="page-link {% if page_obj.number == 2 %}active{% endif %}" href="?{{param_get}}&page=2">2</a>
            {% elif page_obj.number >= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.paginator.num_pages|add:-3 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.previous_page_number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 4 %}
        <li class="page-item">
            {% if page_obj.number <= 3 or page_obj.paginator.num_pages < 5 %}
                <a class="page-link {% if page_obj.number == 3 %}active{% endif %}" href="?{{param_get}}&page=3">3</a>
            {% elif page_obj.number >= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.paginator.num_pages|add:-2 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 5 %}
        <li class="page-item">
            {% if page_obj.number <= 3 %}
                <a class="page-link {% if page_obj.number == 4 %}active{% endif %}" href="?{{param_get}}&page=4">4</a>
            {% elif page_obj.number <= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.next_page_number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.paginator.num_pages|add:-1 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 6 and page_obj.number <= page_obj.paginator.num_pages|add:-3 %}
        <li class="page-item disabled">
            <a class="page-link px-1" href="">{{page_obj.paginator.ELLIPSIS}}</a>
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 2 %}
        <li class="page-item {% if not page_obj.has_next %}active{% endif %}">
            <a class="page-link" href="?{{param_get}}&page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock %}